// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Член Configure не обращается к данным экземпляров, поэтому его можно пометить как статический (Shared в Visual Basic).", Justification = "<Ожидание>", Scope = "member", Target = "~M:WebAppSchool.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"Teachers\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.Position.Teachers")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"Shedules\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.Teacher.Shedules")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1052:Тип \"Program\" относится к статическим заполнителям, однако не является ни Static, ни NotInheritable", Justification = "<Ожидание>", Scope = "type", Target = "~T:WebAppSchool.Program")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"Shedules\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.GroupClass.Shedules")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"Students\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.GroupClass.Students")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"ClassJournals\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.Student.ClassJournals")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"ClassJournals\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.Subject.ClassJournals")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Удалите метод задания свойств для \"Shedules\", чтобы сделать его доступным только для чтения.", Justification = "<Ожидание>", Scope = "member", Target = "~P:WebAppSchool.Models.CodeFirst.Subject.Shedules")]